
services:
  postgres-db:
    image: postgres:latest
    container_name: my-postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    networks:
      - db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  postgres-data:
